// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyChvoDMqXw_5sBbcwYEcihOrVxn7q_CxGU',
    appId: '1:295388771472:web:f0e13ac079a51ce5151415',
    messagingSenderId: '295388771472',
    projectId: 'pomodoro-fb0a7',
    authDomain: 'pomodoro-fb0a7.firebaseapp.com',
    storageBucket: 'pomodoro-fb0a7.firebasestorage.app',
    measurementId: 'G-D6PSPTGE4Q',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBvzBPPX88OzeYZ-FBu8xkGFZ1wUO4cJV0',
    appId: '1:295388771472:android:bd5a2fc48f7060fb151415',
    messagingSenderId: '295388771472',
    projectId: 'pomodoro-fb0a7',
    storageBucket: 'pomodoro-fb0a7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAbBWz-eLaQ06mpwklE-iTnpFmVmEhO1QY',
    appId: '1:295388771472:ios:884d5b70734cac2c151415',
    messagingSenderId: '295388771472',
    projectId: 'pomodoro-fb0a7',
    storageBucket: 'pomodoro-fb0a7.firebasestorage.app',
    iosBundleId: 'app.solidapps.pomodoro',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAbBWz-eLaQ06mpwklE-iTnpFmVmEhO1QY',
    appId: '1:295388771472:ios:884d5b70734cac2c151415',
    messagingSenderId: '295388771472',
    projectId: 'pomodoro-fb0a7',
    storageBucket: 'pomodoro-fb0a7.firebasestorage.app',
    iosBundleId: 'app.solidapps.pomodoro',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyChvoDMqXw_5sBbcwYEcihOrVxn7q_CxGU',
    appId: '1:295388771472:web:d41250623cd5a15e151415',
    messagingSenderId: '295388771472',
    projectId: 'pomodoro-fb0a7',
    authDomain: 'pomodoro-fb0a7.firebaseapp.com',
    storageBucket: 'pomodoro-fb0a7.firebasestorage.app',
    measurementId: 'G-Y37XY4EG12',
  );
}
